version: "3"
services:
  postgres:
    image: postgres
    container_name: semestralka-postgres
    restart: always
    environment:
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: identity
    ports:
      - 5432:5432
  identity-api:
    build: ./identity-api/
    container_name: semestralka-identity-api
    depends_on:
      - postgres
      - identity-gui
    environment:
      PORT: 3030
      JWT_SECRET: shhhhh
    ports:
      - 3030:3030
#   command: npm run migrate &&  node dist/src/index.js
  identity-gui:
    build: ./identity-gui/
    container_name: semestralka-identity-gui
    environment:
       SERVER: http://identity-api:3030
#      HOSTNAME: localhost
#      PORT: 3030
#      HOST: http://$HOSTNAME:$PORT
#      HOST: http://localhost:3030
    depends_on:
      - postgres
    ports:
      - 3000:3000
